### PR TITLE
Add virtual keyboard support

### PR DESCRIPTION
**Pull request by ilyai**
Related link: [Slack](https://ooa.slack.com/archives/CTCQV2U0N/p1700067906345769)

### CODE REVIEW

**Review by mrsln — CHANGES_REQUESTED** [review]
could you please record a video of the keyboard working?
1. pair a BS screen
2. publish web page app with fugo.ai
3. on the screen (record this part):
  1. go to the app
  2. click/tap on the email field
  3. enter staff@fugo.ai
  4. click on the password field
  5. enter the correct password
  6. click log in

**Comment by ilyai** [comment]
@mrsln Not sure if I can try clicking/tapping since there's no port to connect a mouse. I tried displaying the keyboard programmatically though (with `Show()` method), and it worked:  

image

**Comment by mrsln** [comment]
it doesn't have a USB input?

**Comment by ilyai** [comment]
Nope, only HDMI, Ethernet, GPIO and Audio

**Review by mrsln — APPROVED** [review]
ok, it works well

**Pull request merged**
